### ISSUE TITLE
Invalid link in log entry of M2EE unique constraint violation

### ISSUE THREAD

**Issue by bachdble** [mendix/docs#3507]
The following error leads to a bad link.

"APP ERROR M2EE: An error occurred while initializing the Runtime: Detected unique constraint violation [entity: LitigationCommon.Matter, attribute: MatterNumber] For more information on migration, please refer to the Mendix Uniqueness Constraint Migration guide at https://docs.mendix.com/refguide/uniqueness-constraint-migration."

Looks like "https://docs.mendix.com/refguide8/uniqueness-constraint-migration" no longer exists under the Studio Pro 8 Guide.

**Comment by MarkvanMents** [comment]
Hi Mike, @bachdble 
Thanks for pointing out this error.
We removed this documentation from Mendix 9 as database uniqueness is now enforced. The same document is still available in the Mendix 8 documentation and I have asked the development team to change the link in the error message. In the meantime, I will redirect the existing link to the Mendix 8 documentation so that you still get something sensible.
Thanks for drawing our attention to this - it all helps to make our documentation and product better.
Yours
Mark

**Comment by MarkvanMents** [comment]
Redirect tested on development - closing this issue.
