### ISSUE TITLE
XPath "weekday-from-dateTime" documentation incorrect values

### ISSUE THREAD

**Issue by jphenning** [mendix/docs#3583]
The documentation for the XPath function "weekday-from-dateTime" is not correct. It states this:
"Values range from 1 to 7 (1 = Sunday, 7 = Saturday)".

However Mendix running against PostgreSQL results 1 = Monday and 7 = Sunday. I suspect its translating to a database function in PostgreSQL and per the PostgreSQL documentation: "The day of the week as Monday (1) to Sunday (7)".

**Comment by MarkvanMents** [comment]
Thanks for the report @jphenning .
I will investigate this with the developers and update the documentation where necessary.

**Comment by MarkvanMents** [comment]
Hi,
I have discussed this with the developers. They say that they are following this PostgreSQL documentation: https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT. This says 
> dow: The day of the week as Sunday (0) to Saturday (6)

But they add one to this to get a number from 1 to 7.

Unfortunately, I am not in a position to follow this up further. I suggest that the best thing to do is to raise the issue with Mendix Support (https://support.mendix.com) and provide them with more detail, like a sample XPATH which displays this error. If it turns out to be an issue with documentation, they will pass the support ticket on to me.

Thanks again for raising this concern.
Yours
Mark
