### ISSUE TITLE
No sync during sign out action

### ISSUE THREAD

**Issue by linaaaf** [mendix/docs#3710]
An integrated sync during sign out would be a really useful addition.

**Comment by MarkvanMents** [comment]
Thanks for your comment.
This repo is meant for issues with the documentation rather than general suggestions for improvements or requests for help.
I suggest that you make your suggestion via the Mendix forum (https://forum.mendixcloud.com/) where it can receive the backing of other Mendix users. Many suggestions made there find their way into the product.
Thanks again for your positive suggestion.
Yours
Mark
