### ISSUE TITLE
Page Properties

### ISSUE THREAD

**Issue by daeyoungWie** [mendix/docs#4592]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Page Properties](https://docs.mendix.com/refguide/page-properties/)

Document link: [page-properties.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/page/page-properties.md)

## My Issue/Suggestion
![URLConfigured](https://user-images.githubusercontent.com/105832962/169189559-059fe8f3-038a-4d11-bd56-29be4a220e91.png)
add screenshot for better understanding

**Comment by MariaShaposhnikova** [comment]
Hi @daeyoungWie, thank you for your feedback!
Do you mean to update the current screenshot to show where the **Properties** pane is located? Since we have the layout described in the [Studio Pro Overview](https://docs.mendix.com/refguide/studio-pro-overview/) and since users can change the layout of panes, we were aiming at showing only the properties on this screenshot. We have the same standard for widgets, for example, [Data View](https://docs.mendix.com/refguide/data-view/).
If you mean adding the screenshot somewhere else in the document, could you please specify where?

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
@daeyoungWie, as I could not find a problem I will close this issue. If you run into any other issue that the Documentation team can help with, please let us know. You can also try the Mendix Forum or Support if you run into other kinds of errors. 

Best regards,
Maria
