### ISSUE TITLE
Trends in Mendix Cloud v4

### ISSUE THREAD

**Issue by Grasshooper** [mendix/docs#4792]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Trends in Mendix Cloud v4](https://docs.mendix.com/developerportal/operate/trends-v4/)

Document link: [trends-v4.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/metrics/trends-v4.md)

## My Issue/Suggestion
It would be nice if additionally we can also add can additional parameters like max capacity (total file size limit ) which has been provided for the specific node.

**Comment by Grasshooper** [comment]
Something like Used space Total space

**Comment by MarkvanMents** [comment]
Hi Gautam,
Thank you for your feedback.
I understand that you are suggesting additional functionality for the Mendix Cloud graphs rather than more documentation about what they show.
While I could pass your suggestion on to the appropriate development team, it would be better to share the idea on the [Mendix Forum](https://forum.mendix.com/p/ideas). This will give it more weight (coming from the community rather than the documentation team), you will have more visibility of any response from the developers, and it also allows other community members to add their support to your request.

I hope I have understood your request correctly. Please let me know if there are changes that should be made to the documentation, or if you would still like me to pass this on to the development team.
Yours
Mark van Ments
