### ISSUE TITLE
share-marketplace-content

### ISSUE THREAD

**Issue by jasonteunissen** [mendix/docs#5028]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [share-marketplace-content](https://docs.mendix.com/appstore/general/share-app-store-content/)

Document link: [share-app-store-content.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/general/share-app-store-content.md)

## My Issue/Suggestion

not all content types are explained, what are the restrictions of the different types?
this will help users choose the right one.

I don't know what the difference is between a theme, UI resources and layouts, what if we have multiple, and modules that have dependancies

**Comment by Adam-Dupaski** [comment]
Hi Jason, thanks for the feedback. We are aware of this content and category misalignment, and there is a Marketplace project underway to address this. I will not add any definition to themes, layouts, UI resources, and samples now, because it's unclear how these types will be positioned. The rest of the content types remain defined here until an update: https://docs.mendix.com/appstore/general/app-store-overview/#home Cheers.
