### ISSUE TITLE
install-mendix-studio-pro

### ISSUE THREAD

**Issue by DysonQualityAudits** [mendix/docs#5078]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [install-mendix-studio-pro](https://docs.mendix.com/howto/general/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/general/install.md)

## My Issue/Suggestion
[Mendix Native Mobile Builder one-click Installer](https://artifacts.rnd.mendix.com/native-builders/latest.exe)
This link seems to be related to Native Mobile, should sit in a 'Native Mobile' sidebar link?

**Comment by ConnorLand** [comment]
Hi @DysonQualityAudits . The Mendix Native Mobile Builder is indeed related to native mobile. However, it is a tool built-in to Mendix Studio Pro. Thus, it can sometimes affect Studio Pro installations.

It is linked in this document so that if customers are incurring errors, they can try to install the Builder separately before installing Studio Pro to circumvent the error.
