### ISSUE TITLE
data-models

### ISSUE THREAD

**Issue by cyeongb** [mendix/docs#5176]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [data-models](https://docs.mendix.com/howto/data-models/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/data-models/_index.md)

## My Issue/Suggestion
i'm working in samsung sds by using Mendix system. and i think mendix documents need "example code" for developer
not only me, every my collegues said  Mendix should add example code in mendix documents.
i hope this issue is improved ! thank you

**Comment by Adam-Dupaski** [comment]
Hi @cyeongb thanks for the feedback. We do have code samples in docs where those are required and useful, and we're always looking for feedback on docs where code samples could be added or improved. Do you have any such specific examples? Otherwise, Mendix as a low-code platform limits the need for code samples in our docs, as we do forefront visual modeling. Please let me know if you have some specific doc examples here where code samples may be useful.
Thanks.
