### ISSUE TITLE
deep-link

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#5207]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [deep-link](https://docs.mendix.com/appstore/modules/deep-link/)

Document link: [deep-link.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/deep-link.md)

## My Issue/Suggestion

I wanted to open a microflow with multiple parameters, so I tried using the REST Deeplink module in combination with the Deep Link module, which seemed a natural thing to do.  It took me quite a long time to understand why it wasn't working.  When both modules are installed, the Deep Link module stops working.  

1) It would be really helpful if this conflict was highlighted on this page and in the REST Deeplink documentation.  

2) The REST Deeplink module talks about opening pages but makes no mention of opening microflows.  This is a major point of difference that it would be helpful to address in the comparison table between the modules in the Introduction section of this page.

**Comment by MarkvanMents** [comment]
Hi Chris,
Sorry about the very late response to your suggestion.

In the Marketplace we have modules which are platform-supported, and therefore documented in our formal documentation, and some which are community-supported. The community-supported modules are [supported by the developer](https://docs.mendix.com/appstore/general/app-store-content-support/#community-category), rather than Mendix. I realize this is sometimes confusing as the developer can be identified as being part of Mendix.

The REST Deeplink module is a community-supported. In this case, it is down to the developer to ensure that any conflicts with platform-supported modules are documented. Due to the way the Marketplace works, we would not add information about potential conflicts to our documentation of platform-supported components as we might need to review all new components looking for potential issues.

I have contacted the developer in this case and suggested that he adds something to the REST Deeplink documentation to indicate that it is not designed to work with the platform Deep Link module. I've also made him aware of this issue.

In cases like this, it sometimes helps to post on the [Mendix forum](https://forum.mendix.com/p/community) as our community is very knowledgeable and may have found a workaround. Additionally, you can contact the developer directly through the Mendix platform, using the link on the **Developers** tab in the marketplace.

Apologies again for the delay in responding. I'm sorry we cannot include your suggestion in the documentation.
Yours
Mark
