### ISSUE TITLE
environment-planning-for-private-cloud-clusters

### ISSUE THREAD

**Issue by syedaliammar** [mendix/docs#5292]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [environment-planning-for-private-cloud-clusters](https://docs.mendix.com/developerportal/deploy/private-cloud-environments/)

Document link: [private-cloud-environments.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/private-cloud/private-cloud-environments.md)

## My Issue/Suggestion
We should provide the readers helpful material that supports them in making their decision when planning private cloud environments. An example could be to explain licensing, upgrade, security and maintenance perspectives of choosing a single vs multiple namespaces.

**Comment by MarkvanMents** [comment]
Hi Syed,
Thanks for your suggestions.
I have spoken to the development team who agree that more information about upgrading might be helpful, and have added this improvement to their backlog. In the meantime, there is some information about [upgrading just the operator](https://docs.mendix.com/developerportal/deploy/private-cloud-upgrade-guide/) if that would help?

The licensing is explained in the licensing section of [Private Cloud](https://docs.mendix.com/developerportal/deploy/private-cloud/#licensing). As it says in the document, you will need one Operator license for each namespace. I am not clear what additional information would be useful here.

Because the choice to use Mendix for Private Cloud is usually based on your own infrastructure and deployment requirements, it is very difficult to give more advice about maintenance. The decision is often based around the way that cluster managers currently work rather than any requirements that are specific to Mendix.

If you have specific questions about environment planning, I suggest that you post them in the [Mendix Forum](https://forum.mendix.com/p/questions). The Mendix community has a lot of experience and will often have solved the issues you are facing.

Thanks again for making the suggestions - I hope that you will find the additional information about updating useful once the development team have helped in formulating the additional documentation.

Yours
Mark
