### ISSUE TITLE
parse-and-format-date-function-calls

### ISSUE THREAD

**Issue by rondv5** [mendix/docs#5438]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [parse-and-format-date-function-calls](https://docs.mendix.com/refguide/parse-and-format-date-function-calls/)

Document link: [parse-and-format-date-function-calls.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-date-function-calls.md)

## My Issue/Suggestion
When I use the format examples for formatDate in my code I don't get warnings but I do get crashes in execution. Looks like the examples are not valid. Another observation, where is mm representing month listed in the table in the page? I don't see it?
The examples where yyyy/mm/dd are listed, do you mean yyyy/ll/dd (or the caps version thereof)?
I'm confused, this page does not help resolve how I should be using the functions. Can it be adjusted and improved, or can you explain why yyyy-mm-dd does work as 2020-12-16 when the table seems to indicate that it would be minutes for mm?

**Comment by Yiyun333** [comment]
Hi @rondv5:

Thank you very much for your feedback!

In the example yyyy/mm/dd, mm should be MM, and capitalization does make a big difference. We will change this example in the doc. Moreover, if you run into problems with MM, LL (uppercase) is a valid alternative. We are currently working on updating this document to make things more clear.

If you continue to have problems with MM or LL, please raise a support ticket here (https://support.mendix.com/hc/en-us).

Regards,
Yiyun

**Comment by Yiyun333** [comment]
Hi @rondv5:

We've further updated the doc (see PR: https://github.com/mendix/docs/pull/5473). Currently, both the pattern letters M and L work completely as expected in microflows. However, in nanoflows, there are limitations, especially with languages with the genitive case (the month name changes depending on the context). Please see the detailed description in the PR.

Thank you for your patience. We hope that these limitations will be fixed in the future! I am closing this issue. Please raise a new issue if you have further questions.

Best regards,
Yiyun
