### ISSUE TITLE
mendix-feedback

### ISSUE THREAD

**Issue by kosh01** [mendix/docs#5549]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mendix-feedback](https://docs.mendix.com/appstore/modules/mendix-feedback/)

Document link: [mendix-feedback.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/mendix-feedback.md)

## My Issue/Suggestion

We are using this widget in our apps. After submitting the feedback email is sent to all the Team members who are added to the project in Mendix Sprintr. We would like to restrict this only to the specified team members. 

Not sure if this is possible at all but email-related information is not available in the documentation.

Regards,
Abhijit

**Comment by MarkvanMents** [comment]
Hi Abhijit,
Thank you for your feedback.
I think you are getting feedback emails because of the settings in the Developer Portal. These are related to all new items in the app, not just feedback. There is not a separate setting just for feedback items. Have a look at the following documents for more information:

- https://docs.mendix.com/developerportal/collaborate/feedback/
- https://docs.mendix.com/developerportal/#notifications
- https://forum.mendix.com/link/space/other/questions/88194

I hope this answers your question - but let me know if you have further comments on improvements to the documentation.

Often, the forum (https://forum.mendix.com/p/questions) is a good place to ask this sort of question as other members of the Mendix community have often met the same issues and have good suggestions.

Yours
Mark

**Comment by kosh01** [comment]
Thanks, Mark for providing detailed documentation on notifications.

Regards,
Abhijit Koshti
