### ISSUE TITLE
mendix-best-practices-for-development

### ISSUE THREAD

**Issue by TimvanSteenbergen** [mendix/docs#5601]
Page link: [mendix-best-practices-for-development](https://docs.mendix.com/refguide/dev-best-practices/)

Document link: [dev-best-practices.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/dev-best-practices.md)

## My Issue/Suggestion
The best practices as have been suggested by Mendix in the last few years: [Best practices Mx7](https://docs.mendix.com/howto7/general/dev-best-practices/) and [Best practices Mx8](https://docs.mendix.com/howto8/general/dev-best-practices/) 
Standards are best if they only change for the better. You have now changed this from upper-and-lowercase, to only uppercase. So Act->ACT, BCo->BCO etc. This new standard, using only uppercase, is worse, since using only uppercase is less informative and less readable. "After create" is easier to recognise in ACr compared to in ACR, since the latter suggests that it is an abbreviation of three words.
Fix: Reset the prefixes to the same that Mendix has had for the last years.

**Comment by Adam-Dupaski** [comment]
Hi @TimvanSteenbergen thanks for the feedback. We are still with aligned with how Academy is teaching these best practices and with what Mendix Expert Services advises, so that's what we are basing this documentation on. Therefore, the comments/response in this PR are still most relevant: https://github.com/mendix/docs/pull/4528

Cheers,
Adam
