### ISSUE TITLE
saml IDP config toggle active deactivating on its own

### ISSUE THREAD

**Issue by szarrinkelk** [mendix/docs#5613]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [saml](https://docs.mendix.com/appstore/modules/saml/)

Document link: [saml.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/saml.md)

## My Issue/Suggestion

IDP toggle automatically seems to toggle to No while still displaying Yes within the IDP config tab. This leads to the SSO login page to show a 404 nginx not found page. The only way to resolve this for now is logging in as MxAdmin and reactivating the idp by clicking the toggle active button twice. This is a not a sustainable solution though since this keeps happening and we can't seem to recreate what causes this and just have to be alert to manually fix whenever this happens.

**Comment by MarkvanMents** [comment]
Hi,
This feedback route is aimed at making corrections to the Mendix documentation rather than reporting issues.
I have passed your report on to the team responsible for the SAML SSO module, but have not had any feedback yet.
If you want to raise an issue which you can track and enter extra information if needed, I recommend that you either:
* ask a question on the [Mendix forum](https://forum.mendix.com/p/community) where there are many experienced community members who may be able to help you.
* raise a ticket with [Mendix Support](https://support.mendix.com/hc/en-us) who can follow up with the development teams to identify the issue and get it fixed if possible.

Thanks for your feedback to Mendix, it all goes to make a better product. Please feel free to raise further issues and suggestions with the documentation through this feedback mechanism.
Yours
Mark
