### ISSUE TITLE
Need a version switcher on each document page

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#6028]
I am in Expert Service team in Mendix. This suggestion comes from voices of many clients.

I suggest that we should add a version switcher on each page of our document. The version number sould be in the URL of each page, not only for the old version, but for the current version. They are very common in many mature software documents, e.g. [ReactNative](https://reactnative.dev/docs/flexbox), [NodeJS](https://nodejs.org/dist/latest-v18.x/docs/api/all.html).

Reasons:
1. Many versions are currently being used by our clients. It is hard for them to tell whether the document page is fit for their currently using version, especially for the Developer Portal Guide and Marketplace Guide.
2. Many users are using MX9 or MX8, but external links ( from Community or StackOverflow) are always pointing to the latest MX version ( current MX 10). Clients without high sense of versioning will be misled. So we need the version number be in the  URL of each page.

**Comment by MarkvanMents** [comment]
Hi Jinheng,
Thank you very much for the suggestion. We looked into this when we updated our stack last year and couldn't implement it immediately because of the way the stack is built.
However, I have added your comments to our backlog of improvements and would definitely like to make things easier, if possible.
There are various technical issues to consider (e.g. what happens if we delete, move, or rename a document in a particular version) but this doesn't block the general principle.
In the meantime, you can tell from the URL (e.g. refguide is Mendix 10 - the latest version, refguide9 is Mendix 9, etc.) - leaving the number off the latest version means that Google places the latest version highest and we don't have to wait for a reindex when the site changes, which is why we don't include the version number.
And you can also search on a particular version in the documentation page header by choosing the appropriate **Space**.
I will close this issue for now, but please let me know if you have any further thoughts or suggestions.
(Since you are internal, you can also send us suggestions via Slack if that is easier).
Yours
Mark van Ments
