### ISSUE TITLE
There are no instructions for linux versionsruntime-server

### ISSUE THREAD

**Issue by yinzx666** [mendix/docs#6035]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [runtime-server](https://docs.mendix.com/refguide9/runtime-server/)

Document link: [runtime-server.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/runtime/runtime-server.md)

**Comment by MarkvanMents** [comment]
Hi Zxue Yin,
The document you were reading is a generic description of how the runtime works to interpret the Mendix model you create in Studio Pro. This then needs to be deployed to a (usually cloud) platform in order to run. The various instructions for these are in the [Deployment](https://docs.mendix.com/developerportal/deploy/) section under the **Developer Portal**.

I'm not sure from your issue exactly how you want to deploy your Mendix app, but there are instructions there for [Unix-Like Deployment](https://docs.mendix.com/developerportal/deploy/unix-like/) as well as using [Docker](https://docs.mendix.com/developerportal/deploy/docker-deploy/).

I hope that one of these (or one of the other deployment solutions listed there) is helpful. If not, the best place to ask for help is either [Mendix Support](https://support.mendix.com/hc/en-us) or the [Mendix Forum](https://forum.mendix.com/index3.html).

If you feel that a specific document is still needed, please do let us know - with more details on exactly what you are looking for - and we can then add this need to our backlog of documents to be written.

Thank you for taking the time to contact Mendix.
Yours
Mark van Ments.
