### ISSUE TITLE
runtime-customization

### ISSUE THREAD

**Issue by GautamJ700** [mendix/docs#6051]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [runtime-customization](https://docs.mendix.com/refguide/custom-settings/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/custom-settings/_index.md)

## My Issue/Suggestion
On 100% chrome browser setting some part of text is getting chopped of , once reduced to 90 % it works fine .Attached SS for more information .
![Screenshot General settings](https://github.com/mendix/docs/assets/115712743/77fe839f-f036-4b62-8b96-92e9b578d247)

**Comment by MarkvanMents** [comment]
Hi @GautamJ700 
Thanks for the report.
We are aware that this happens when the browser window is not the full width of the screen. When the browser is expanded, the table does fit, in the tests we have done so far. You can also scroll the table to the right, but the scrollbar is right at the bottom of the table and you then lose the left-hand side, so it isn't a great solution.
The issue is that many of the setting names are long and don't wrap. We could set wrapping to not be on word boundaries, but this will lead to tables which are more difficult to read. We have tried to address the problem with adjusting the CSS and changing the table content, but it seems that we can't get rid of the issue totally.

The other option is to avoid the use of tables for listing these settings - but the table format is generally the best way to present this information, when it works.

This is on our backlog to look at, but it looks like it needs the involvement of a CSS expert to see if it can be improved from that point of view.

Sorry I can't be more positive about a short-term solution.

Thanks for the report and for wanting to improve the Mendix documentation.

Yours
Mark van Ments
