### ISSUE TITLE
anonymous-users

### ISSUE THREAD

**Issue by tselina** [mendix/docs#6067]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [anonymous-users](https://docs.mendix.com/refguide9/anonymous-users/)

Document link: [anonymous-users.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/app-explorer/security/app-security/anonymous-users.md)

## My Issue/Suggestion

There is no way to clean field "Anonymous user role" within App -> Security -> Anonymous users if that once been selected.

I would suggest to create some way to clean that for the case

**Comment by MarkvanMents** [comment]
Hi Dmytro,
Thanks for getting in contact with us.
Unfortunately, these GitHub issues are solely for problems with the documentation. As far as I understand it, you are suggesting an improvement to the product rather than a problem with the documentation.
My understanding, from the documentation, is that you can enable anonymous users and then you need to choose a role for them (otherwise the app security will not know what the use can or can't do).
If you have a suggestion for how this can be improved in the product, the best place is to add an idea on the [Mendix forum](https://forum.mendix.com/p/ideas). Then other Mendix users can discuss and support the idea and it can be picked up in future releases.
If you think the documentation could be clearer in any way, please do raise another issue. The quality of our documentation is dependent on customers noticing things that are wrong or could be improved.
Yours
Mark van Ments
