### ISSUE TITLE
data-sources

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#6096]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [data-sources](https://docs.mendix.com/refguide9/data-sources/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/pages/data-widgets/data-sources/_index.md)

## My Issue/Suggestion

Can we improve the context regarding Native Mobile applications and which database is queried either Server DB or Mobile DB? It's not that clear. 
It says, "Database and nanoflow data sources are the only data sources supported offline." however speaking with a colleague XPath data source is also available offline. Apparently, it all depends on the context, if you're in a microflow a DataSource XPath will go the Server DB. If you're on a Native Page / nanoflow, it'll go to the local DB. Can we update the docs if this is indeed true?

**Comment by MarkvanMents** [comment]
Hi Elliot,
The front-end developers say that data is always taken from the offline database and pointed me at https://docs.mendix.com/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data where the introduction makes it clear that:

> Pages and logic interact with an offline database on the device, and the client synchronizes the data with the server.

I think this is the best place for this information as, if people are writing an offline app, they will use this document. To me, it implies that an XPath will use the offline database as it is only another way of retrieving information from the database.

If you have further concerns, I suggest that you raise the issue in Slack (or the Mendix forum) so that all the aspects can be discussed properly, rather than me acting as an intermediary.
