### ISSUE TITLE
debugging-microflows-remotely

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#6105]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [debugging-microflows-remotely](https://docs.mendix.com/refguide/debug-microflows-remotely/)

Document link: [debug-microflows-remotely.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/debug-microflows-and-nanoflows/debug-microflows-remotely.md)

## My Issue/Suggestion
Is it possible to remote debug my application if my application is deployed:
1. On-premise on a Linux OS.
2. With docker in a k8s cluster ( without Mendix Operator )?

If possible, how to?

**Comment by MarkvanMents** [comment]
Hi Jinheng Zhu,
Sorry that I have taken so long to get back to you.
Thank you for drawing our attention to the lack of documentation on this topic. 

I think it is possible and I did find this solution in StackOverflow ([Mendix: enabling debugger in docker container](https://stackoverflow.com/questions/70800098/mendix-enabling-debugger-in-docker-container)) which might also be able to help you. This feedback is intended for reporting issues with documentation rather than getting answers to specific questions. In future, you can ask questions like this on the [Mendix Forum](https://forum.mendix.com/p/questions) where many experienced Mendix developers are able to help you.

In the meantime I will make a task to add this to our documentation in the future to help other developers.

Thank you for contacting Mendix and helping make our documentation better.
Yours
Mark
