### ISSUE TITLE
private-cloud-cli-non-interactive

### ISSUE THREAD

**Issue by keving119** [mendix/docs#6215]
Running it non-interactive doesn't really make sense if the docs don't explain the right .yaml structure. Right now, it only provides an example that does not work, and I cant find a working example anywhere. So I should first run it interactive and apply the yaml to get an example. Doesn't make any sense.

**Comment by katarzyna-koltun-mx** [comment]
Thank you for reporting the issue! I will verify it with the team and update the document accordingly.

**Comment by katarzyna-koltun-mx** [comment]
@keving119 The development team have asked for more information about the issue that you encountered when trying to use the example yaml. Was it related to the allowOverrideSecretsWithSecretStoreCSIDriver field?

**Comment by katarzyna-koltun-mx** [comment]
After discussing the issue with the development team, I have the following updates:

- Generating your own yaml file as you did is indeed the recommended version. There are many potential variables that depend on individual configuration, so we cannot provide an example that would work for everyone.
- Because of that, I have updated the document (https://docs.mendix.com/developerportal/deploy/private-cloud-cli-non-interactive/#3-apply-configuration) to make it clearer that the provided sample file is for reference only.

Thank you and let us know if you have any other feedback for our documentation.
