### ISSUE TITLE
sign-in-button

### ISSUE THREAD

**Issue by joshsonofmichael** [mendix/docs#6241]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [sign-in-button](https://docs.mendix.com/refguide/sign-in-button/)

Document link: [sign-in-button.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/authentication-widgets/sign-in-button.md)

## My Issue/Suggestion
I couldn't find any explanation for how the actual sign in logic is executed. I was trying to figure out if there was a way to link it to a specific entity (after some other digging I'm now pretty sure it's only linked to the system.user). It might not be an issue for more experienced mendix users but I was surprised there wasn't any mention of or even link to an explanation of what clicking the button actually does.

**Comment by MarkvanMents** [comment]
Hi Josh,
Thanks for pointing out this gap in the documentation. We are aware that the description of security is not as complete as it might be and have an ongoing task to improve it.  I will add your issue to the plans for that. Our current security information is here: [Security](https://docs.mendix.com/refguide/security/).
Because Mendix is low-code, there is an expectation that most users will just pick up the sign-in button widget and add it where appropriate. They then know that, if the end-user clicks it, they can successfully sign in to the app and the appropriate app security will be applied to their session. However, I realize that this is not always enough information if you want to use this information for other things.
You are correct that the system.user entity is the one which controls whether a user is signed in or not.

If you have specific questions about how things work, I recommend that you ask on the [Mendix Forum](https://forum.mendix.com/p/questions) where many Mendix developers can help you.

Thanks for the suggestion to improve the Mendix documentation and wanting to make it better for our community.
Yours
Mark
