### ISSUE TITLE
document-templates

### ISSUE THREAD

**Issue by Karuna98567** [mendix/docs#6317]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [document-templates](https://docs.mendix.com/refguide/document-templates/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/document-templates/_index.md)

It would be great if you can upload the explanations over vedio on 'Document Template' Concept

**Comment by katarzyna-koltun-mx** [comment]
Thank you for reaching out to us - I will pass the suggestion to the documentation owner, so that we can review the document and decide on the best way to improve it. Can you let me know why a video would be useful in this case? Would you like a practical example, or would it be useful to see a sequence of steps, or another reason?

**Comment by katarzyna-koltun-mx** [comment]
I'm going to close the issue for now, but please let me know if you'd like to discuss the above.
