### ISSUE TITLE
data-widgets

### ISSUE THREAD

**Issue by liouwe-lcc** [mendix/docs#6384]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [data-widgets](https://docs.mendix.com/appstore/modules/data-widgets/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/data-widgets/_index.md)

## My Issue/Suggestion
Make the mentioned widget availble in the marketplace within Mendix Studio pro

**Comment by ConnorLand** [comment]
Hello,

I just searched in the Studio Pro's Marketplace tab with "data widgets" and the data widget module did come up at the top of the results. I think what helped this is that I kept "all content types" selected in the dropdown, so that when I searched for it it came up even though it is a module (not a widget, as the name might suggest).

I hope this helps. Thank you for reaching out to documentation.

Connor
