### ISSUE TITLE
tree-node

### ISSUE THREAD

**Issue by JhansiMora** [mendix/docs#6482]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [tree-node](https://docs.mendix.com/appstore/modules/tree-node/)

Document link: [tree-node.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/data-widgets/tree-node.md)

## My Issue/Suggestion
Hi Mendix,
I am Jhansi Mora,
My working email id is jhansilaxmi.mora@erieinsurance.com.

I would like to get more information on the animation option when selected. While I am trying my code, I don't see any difference when applied. It would be great if animation option is explained in detailed.

Also I don't see the visualization tab having the collapse and expand icon working. I am not sure if they are working or no. Some more information would be great.

Appreciate your response!!!
Thanks,
Jhansi Mora

**Comment by ConnorLand** [comment]
Hello,

I am in discussions with the developers and we will take a look into clarifying this matter. 

Thank you for your query,

Connor

**Comment by ConnorLand** [comment]
Hello,

The developers have made a JIRA story to update both the widget and the documentation based on your feedback (and other users'). Because this issue is now in our company's development planning, I am going to close your feedback item. But rest assured, we will make the improvements to the tech and docs.

I'll also circle back and message you when the improvements have been made.

Thank you for contributing to the documentation,

Connor

**Comment by JhansiMora** [comment]
Appreciate for the reply!


Thanks,
Jhansi Mora
