### ISSUE TITLE
datadog-for-the-mendix-cloud

### ISSUE THREAD

**Issue by TwiggyWiggy** [mendix/docs#6497]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [datadog-for-the-mendix-cloud](https://docs.mendix.com/developerportal/operate/datadog-metrics/)

Document link: [datadog-metrics.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/metrics/monitoring-with-apm/datadog-metrics.md)

## My Issue/Suggestion
https://docs.datadoghq.com/getting_started/site/
**5.2 Datadog Regions (DD_SITE)
The valid values for DD_SITE are:
datadoghq.com
datadoghq.eu**

This statement is not accurate anymore, as there are more regions now, refer to the Datadog link below.
https://docs.datadoghq.com/getting_started/site/

SITE | SITE URL                                     | SITE PARAMETER         | LOCATION
US1 | https://app.datadoghq.com       | datadoghq.com           | US
US3 | https://us3.datadoghq.com        | us3.datadoghq.com    | US
US5 | https://us5.datadoghq.com        | us5.datadoghq.com    | US
EU1 | https://app.datadoghq.eu          | datadoghq.eu              | EU
US1-FED | https://app.ddog-gov.com | ddog-gov.com             | US
AP1 | https://ap1.datadoghq.com       | ap1.datadoghq.com    | Japan

**Comment by MarkvanMents** [comment]
Hi @TwiggyWiggy 
Thanks for identifying this and for your suggestion. I have updated the documentation here: https://github.com/mendix/docs/commit/34b6aa3f6b18badd717c9b2cddc440d88baa7fcb. We now point to Datadog's list of sites so that our documentation will stay up to date.
The developers are unable to test all these endpoints, but are confident that they will work. If you have any issues using them, please let us know.
Yours
Mark van Ments
