### ISSUE TITLE
data-grid-2

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#6568]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [data-grid-2](https://docs.mendix.com/appstore/modules/data-grid-2/)

Document link: [data-grid-2.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/data-widgets/data-grid-2.md)

## My Issue/Suggestion

As Data Grid 2 is one of the most important widgets out of the box, but there is no demo or use case document. Other widgets from the marketplace commonly have demos or use cases.
So I strongly suggest we provide some demo and use case documents for the built-in widgets.

**Comment by ConnorLand** [comment]
Hello @zjh1943,

Data Grid 2 is indeed a robust module, and could benefit from more use-case examples. I think the best way to showcase DG2 possibilities is via a Mendix Academy Learning Path. Due to your comment, I am working with Academy to help them make a Data Grid 2 learning path. This might take a couple months to publish, however, so please use the [Mendix Forum](https://forum.mendix.com/index3.html) if you have specific inquiries about DG2 best practices.

We also have [a blog entry](https://www.mendix.com/blog/mendix-9-2-0-a-modern-grid-for-a-multi-experience-world/) discussing DG2 which provides a little more guidance.

Thank you for your idea, and I'll mail you back when we have the Learning Path published.

Connor
