### ISSUE TITLE
microsoft-teams

### ISSUE THREAD

**Issue by miikkij** [mendix/docs#6591]
If you deprecate something, could you please tell why it was deprecated? 

Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [microsoft-teams](https://docs.mendix.com/appstore/connectors/ms-teams-connector/)

Document link: [ms-teams-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/connectors/ms-teams-connector.md)

**Comment by Luyao-Zhang-1** [comment]
@miikkij Thank you for sending us the feedback! We will try to make sure that we include reasons and/or alternatives (if there is any alternative) for deprecated features in the docs.

As for Microsoft Teams Connector, it is deprecated because Mendix has decided to stop offering app services, which includes Microsoft Teams Connector.
