### ISSUE TITLE
calendar issues

### ISSUE THREAD

**Issue by chaehyeon01** [mendix/docs#6612]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [calendar](https://docs.mendix.com/appstore/widgets/calendar/)

Document link: [calendar.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/calendar.md)

## My Issue/Suggestion

Hello, I'm using the Calendar widget in my project. As the Mendix version rises to 10, the Calendar widget looks like it needs a full update. Please update the widget :(

[Some issues in version 9]
1. The button item attribute value 'Header day format' of 'Custom top bar views' is not changed properly. (When changed, the 'Title date text' date format changes together). )

2. I changed the default language for the project ', but 'Titledate text' is not formatted properly.
(Does not change to project default date format. )
Project Date format -> yyyy MM
calendar Date format -> MM yyyy

I want to change 'Title date text' to yyyy MM format. But it doesn't work out.

**Comment by ConnorLand** [comment]
Hello @chaehyeon01 ,

I've spoken to one of our developers who specializes in Calendar. Without a test app, it's hard for us to confirm the causes of your issue because Calendar has so many configuration options and edge cases. However, this might be a valid issue for feedback.

Could you please open a [Support request](https://docs.mendix.com/developerportal/support/submit-support-request/) on this issue? You can copy/paste the text you've used here, and include screenshots if you have them. If Support recognizes documentation errors after helping you, they'll reach out to me and I will change the documentation.

Thank you for raising this concern,

Connor
