### ISSUE TITLE
html/javascript-snippet

### ISSUE THREAD

**Issue by wang3156** [mendix/docs#6694]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [html/javascript-snippet](https://docs.mendix.com/appstore/widgets/html-javascript-snippet/)

Document link: [html-javascript-snippet.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/html-javascript-snippet.md)

## My Issue/Suggestion
![image](https://github.com/mendix/docs/assets/18094713/345e1734-5e88-4c3c-93ed-1f9032839907)
The path to o.p here is /widgets/, which causes a path error when my site path has a virtual directory

**Comment by ConnorLand** [comment]
Hello @wang3156 ,

Thank you for this valuable feedback. Because it is concerning the code file inside the widget, and not the code snippet in the document, could you please file a [Support Ticket](https://support.mendix.com/hc/en-us) if this is a blocking issue for your app work? The developers will then be alerted to the issue and change the code.

Thank you,

Connor
