### ISSUE TITLE
maps documentation

### ISSUE THREAD

**Issue by IsmailBulgur** [mendix/docs#6701]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [maps](https://docs.mendix.com/appstore/widgets/maps/)

Document link: [maps.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/maps.md)

## My Issue/Suggestion

When using the official MX Maps widget, nothing showed up even when the Maps was placed correctly with a Google Maps API key provided. However, providing **Map Styles** in the **Advanced** tab with {} (JSON array with Google Maps styles.) did the trick and the map showed finally. Can this specific information be provided in the description of Maps, because leaving the **Map styles** empty won't show a map in our case with Mendix 9.24.10. 

Maybe it's good to add that you need to enter something of a JSON array. 
![Schermafbeelding 2023-10-25 123329](https://github.com/mendix/docs/assets/99026524/3cbeda3b-1101-44f1-9422-27a56ae842f6)

**Comment by ConnorLand** [comment]
Hi @IsmailBulgur ,

You are not alone. Other users have had issues with the Map widget in the last few months. As this issue is fundamentally to do with widget functionality first, and documentation second, please file a [Support Ticket ](https://support.mendix.com/hc/en-us) with Mendix Support. Just copy and paste the text and screenshot from this issue please.

They will give you some Maps best practices, your feedback might help improve the widget, and if Support needs documentation changes I will make them.

Thank you for reaching out to documentation,

Connor

**Comment by ConnorLand** [comment]
Hi again @IsmailBulgur ,

I just wanted to circle back and let you know that I included guidance -- and your screenshot -- in the **Basic Usage** section of the _Maps_ document. These additions will be on our website in a few minutes. Thank you for helping me improve the Mendix docs.

Best, 

Connor
