### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by EmmavdBoom** [mendix/docs#6775]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [layout](https://docs.mendix.com/refguide/layout/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/page-resources/layout/_index.md)

## My Issue/Suggestion

The Master layout is explained, but it doesn't tell you how you can set the default of the master layout.

**Comment by ConnorLand** [comment]
Hello @EmmavdBoom ,

From one of our developers, "there is no "default" master layout for an app, at the very least. It's a per-layout option to base a new layout on another instead of creating it fully from scratch". We do have several instructions in the document on how you can speed up development by using generic/primary layouts. Does that clear the issue up?

Connor
