### ISSUE TITLE
How to migrate to Git if there are 1000 or more revisions?

### ISSUE THREAD

**Issue by axelenexis** [mendix/docs#6887]
Page link: [migrate-to-git](https://docs.mendix.com/developerportal/general/migrate-to-git/)

Document link: [migrate-to-git.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/general/team-server/migrate-to-git.md)

## My Issue/Suggestion
What to do if the version control history consists of 1000 commits or more?

**Comment by tknippenberg** [comment]
At this point there is no way to migrate to Git if you have more than 1000 commits and/or an .mpr file that's larger than 100MB. For the latter there are some tricks that help you scrape off a little bit of the size, but the commit limitation is not something you can currently circumvent.

We have implemented this limitation because we have had some cases where developing a relative large app became slower after migrating from SVN to Git, because Git works differently with your history (it downloads everything by default, where SVN only downloads the latest revision).

Several R&D teams are currently working on ensuring we can lift the migration limitations in the coming quarter:

1. Changing the .mpr storage format. Currently we have 1 large binary, which is suboptimal for version control systems. By changing this format we will reduce the growth rate of your repository.
2. Enabling Studio Pro to better handle large repositories, for example by using a shallow clone (not downloading the full history)
3. Cleanup script to remove a part of your version control history, as number 1 won't address the history you have already accumulated

**Comment by kleineroscar** [comment]
Hey @tknippenberg ,
is there any update you can provide for this topic?

**Comment by tknippenberg** [comment]
On 1 February we've sent communications to technical contacts of customers that are currently blocked from migrating. Progress on the three tracks I mentioned above is still ongoing.

1. Changing storage format to prevent issues going forward: aiming for Q2 2024.
2. Enabling Studio Pro to better handle large repositories: after the other measures, more likely H2 2024.
3. Cleanup script: currently there is an ongoing private beta, for which you can apply by contacting your CSM.
