### ISSUE TITLE
migrate-your-mendix-database

### ISSUE THREAD

**Issue by pietervercammen** [mendix/docs#7098]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [migrate-your-mendix-database](https://docs.mendix.com/howto/data-models/migrating-your-mendix-database/)

Document link: [migrating-your-mendix-database.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/data-models/migrating-your-mendix-database.md)

## My Issue/Suggestion

SAPHANA is missing here, but we mention it in our docs: https://docs.mendix.com/refguide/custom-settings/#43-migration-settings

**Comment by MarkvanMents** [comment]
Hi Pieter,
Sorry about the delay in getting back to you.
I'm not sure what you think is missing from this document? In [Migrate Your Mendix Database](https://docs.mendix.com/howto/data-models/migrating-your-mendix-database/) sections 5.2.2 and 5.2.3 explain how to migrate your database to SAP HANA.

Could you perhaps explain your use case and what is missing from the documentation?

Thanks for contacting us and suggesting improvements to the documentation. I look forward to hearing a bit more detail so that I can take this forward.
