### ISSUE TITLE
OQL error after installing module in my App (Mendix 10.6.1)

### ISSUE THREAD

**Issue by Iker-Inetum** [mendix/docs#7128]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [oql](https://docs.mendix.com/refguide/oql/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/data-sets/oql/_index.md)

Hi,

After installing the OQL module in my Mendix app in 10.6.1 version and try to run it, the app retunrs and error. The error is not showing in Mendix Log, but when i run the aplication returns an error and stop running.
I also have installed this modules: DatabaseReplication, DataWidgets, MxModelReflection and WebActions.
Can you help me to resolve this issue?
Thanks in advance,

**Comment by MarkvanMents** [comment]
Hi @Iker-Inetum 
This feedback is for errors and improvements to documentation, so I'm afraid I can't help you resolve your issue.
The best places to ask for help about this are:

- The [Mendix Forum](https://forum.mendix.com/p/questions) – where other members of the Mendix community can help you
- [Mendix Support](https://support.mendix.com/hc/en-us)

Please let us know if the issue turns out to be related to bad or missing documentation.
Yours
Mark
