### ISSUE TITLE
reference-selector

### ISSUE THREAD

**Issue by RCatersels** [mendix/docs#7366]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [reference-selector](https://docs.mendix.com/refguide/reference-selector/)

Document link: [reference-selector.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/input-widgets/reference-selector.md)

## My Issue/Suggestion
The Constrained By function should get it's own header (so 3.10.3) since it is completely independent of XPath constraints. See also the doumentation of Mx7 (https://docs.mendix.com/refguide7/reference-selector/) where it does get it's own header. Now when searching on Constrained by you will always see the Mx7 version first.

**Comment by MarkvanMents** [comment]
Hi Ronald.
Thanks for your suggestion.
I have taken the opportunity to restructure this section a bit in #7380 . Unfortunately, I don't think I can restructure it enough to have the section for Mendix 10 found before the Mendix 7 version. That would mean completely restructuring the Mendix 7 page to use lower-level headings, which is not worth it since it is not supported any more.

We are looking at improving Google's sorting of our pages to try to improve this, but this is likely to be a fairly long project as SEO is a bit of a black art.

Thanks for reporting this and helping improve the Mendix documentation.
Yours
Mark van Ments
