### ISSUE TITLE
dynatrace-for-mendix-cloud

### ISSUE THREAD

**Issue by lucadesimoni** [mendix/docs#7396]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [dynatrace-for-mendix-cloud](https://docs.mendix.com/developerportal/operate/dynatrace-metrics/)

Document link: [dynatrace-metrics.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/monitoring-with-apm/dynatrace-metrics.md)

## My Issue/Suggestion

Apparently no one from mendix or dynatrace can support on this documentation, integration is not working, please improve documentation, or state limitations.

**Comment by dbreseman** [comment]
Hi @lucadesimoni, thanks for reaching out. Could you please share some more details about the issue you're experiencing so that I can address it in the documentation?

**Comment by lucadesimoni** [comment]
Hi @dbreseman
Unfortunately, we are not able to properly configure dynatrace integration, but do not get any error, so looks like the documentation is either incomplete or does not reflect the proper integration procedure.

**Comment by dbreseman** [comment]
I see—sorry to hear the integration hasn't been working out for you. I can confirm that our Dynatrace integration instructions have been successful on other systems, so it could be that you've encountered a new edge case. If you post on [Mendix Community](https://community.mendix.com/p/community) or reach out to [Mendix Support](https://support.mendix.com/hc/en-us), they may be able to assist with troubleshooting. If the issue is related to Dynatrace access, then I recommend reaching out to [Dynatrace Support](https://one.dynatrace.com/hc/en-us/requests).
