### ISSUE TITLE
pipelines-beta

### ISSUE THREAD

**Issue by fitterup** [mendix/docs#7517]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [pipelines-beta](https://docs.mendix.com/developerportal/deploy/pipelines/)

Document link: [pipelines.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/mendix-cloud-deploy/pipelines.md)

## My Issue/Suggestion
Add information if a start pipeline is started on a recurring schedule, will it always run or will it check if there is also a new commit?

**Comment by dbreseman** [comment]
Hi @fitterup, thanks for raising this issue.

Each pipeline can only have one start trigger, and the two possible trigger types (Recurring scheduled and Teamserver push) are independent from one another. This means that the following is true:
- If you want your pipeline to run according to both triggers (say, every time you push to your main branch and every Monday at noon), you can create and activate a separate version of the pipeline for each trigger.
- If a pipeline is set to run on a recurring schedule, it will run the entire pipeline even if there haven't been any changes to the branch since the last time the pipeline ran.

I hope this helps clarify things! Please do let me know if something remains unclear.

Best,
Dana
