### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by Marcell0oo0** [mendix/docs#7615]
Page link: [websockets](https://docs.mendix.com/refguide/websockets-in-runtime/)

Document link: [websockets-in-runtime.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/websockets-in-runtime.md)

## My Issue

In some communication protocol, which is based on WebSocket, we need to read and write the opening **handshake** **header**. In Java we can do this with [modifyHandshake](https://docs.oracle.com/javaee%2F7%2Fapi%2F%2F/javax/websocket/server/ServerEndpointConfig.Configurator.html#modifyHandshake-javax.websocket.server.ServerEndpointConfig-javax.websocket.server.HandshakeRequest-javax.websocket.HandshakeResponse-)

public void modifyHandshake([ServerEndpointConfig](https://docs.oracle.com/javaee%2F7%2Fapi%2F%2F/javax/websocket/server/ServerEndpointConfig.html) sec, [HandshakeRequest](https://docs.oracle.com/javaee%2F7%2Fapi%2F%2F/javax/websocket/server/HandshakeRequest.html) request, [HandshakeResponse](https://docs.oracle.com/javaee%2F7%2Fapi%2F%2F/javax/websocket/HandshakeResponse.html) response)

![image](https://github.com/mendix/docs/assets/167408240/898d7279-1412-4c1c-b8be-1a8de3d7e718)
[[wiki/WebSocket](https://en.wikipedia.org/wiki/WebSocket)]

For example there is a communication protocol, where there is different versions, and the client writes in the header, what versions they are accept. So we need to read it form the header, for example (MyProtocolVersion : 3.4, 4.5 ), and respond (MyProtocolVersion : 3.4) or (MyProtocolVersion : 4.5)

In the future is it possible that we will have access to it?

### My suggestion: 
Mendix will still handle the headers, except the "Other headers", so we can **read** it and do something in Java then **write** the **"Other headers"**, and based on the value, say no to the client, so no websocket connection will made. And I also want to read the URI during the handshake, because in the protocol that I want to implement, the clients put his ID after the "ws://.../my-endpoint" like this ws://.../my-endpoint/ClientID

**Comment by MarkvanMents** [comment]
Hi,
Thanks for raising this issue.
Unfortunately, this repo is for reporting issues with the documentation. You seem to be requesting a new feature. The best place to do this is on the [Community Ideas](https://community.mendix.com/p/ideas) page. There you can get support for your ideas from other members of the community, and they can be picked up by the development teams.
I suggest that you put this request there so that it gains traction from the community.

Thanks for your suggestions for making Mendix better.
Yours
Mark van Ments.
