### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by CAPE-Rudolf** [mendix/docs#7677]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [webhooks](https://docs.mendix.com/developerportal/deploy/webhooks/)

Document link: [webhooks.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/general/webhooks.md)

## My Issue

When using the Custom Header "Authorization" with the webhook. It is gone when you re-open the webhook.
Maybe this is because it's hiding it on purpose but it is now unclear what is configured.
Using other Header names is fine and they stay visible.
Right now I'm not even sure if the header is there and invisible or if it's unable to save it with the "Authorization" name.
Can't get the Webhook to work anymore either way.

**Comment by dbreseman** [comment]
Hi @CAPE-Rudolf,
Thanks for raising this. Custom Authorization headers are considered sensitive and thus do not display in the custom header list. The Authorization header otherwise behaves just like the other custom headers, and it should be visible in the webhook response if you click Test Webhook. I added a note to the Webhook documentation to clarify this: https://github.com/mendix/docs/commit/806790f6e989ed47082456701a6af210112d2abd. These changes should be live by the end of the day.
Thank you for helping to improve the Mendix Docs.
Kind regards,
Dana
