### ISSUE TITLE
set-up-your-partner-profile

### ISSUE THREAD

**Issue by JustSolveSolutions** [mendix/docs#7774]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [set-up-your-partner-profile](https://docs.mendix.com/community-tools/how-to-set-up-your-partner-profile/)

Document link: [how-to-set-up-your-partner-profile.md](https://github.com/mendix/docs/blob/development/content/en/docs/community-tools/how-to-set-up-your-partner-profile.md)

## My Issue/Suggestion
Good day, the Mendix Customer Support Engineer, requested me to log a support ticket here, stating: If no one is authorized to be Partner Editor at the moment, click Feedback on the right side of the screen and submit a feedback item to gain access.

I hope I'm following the process accurately. 
Currently my company does not have a "clickable" company link as described in support ticket: https://support.mendix.com/hc/en-us/requests/217643

Please advise.

**Comment by MarkvanMents** [comment]
Hi,
I have spoken with the support engineer and there seems to have been a miscommunication. The feedback you need to click is on the site rather than the documentation.
I will close this documentation issue and hope that you manage to resolve your issues with the help of customer support.
Yours
Mark
