### ISSUE TITLE
system-requirements

### ISSUE THREAD

**Issue by avotom** [mendix/docs#7886]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [system-requirements](https://docs.mendix.com/refguide/system-requirements/)

Document link: [system-requirements.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/installation/system-requirements.md)

## My Issue/Suggestion
We recently had an issue (I believe with the firewall) after upgrading from 10.8 to 10.11, because gradle was not able to fetch dependencies. Therefore I think plugins.gradle.org should be added to the required firewall settings.

**Comment by MarkvanMents** [comment]
Hi there,
Thanks for your suggestion.

We recently made an update, #7343 which added this information to the [Managed Dependencies](https://docs.mendix.com/refguide/managed-dependencies/#72-vpn-setup) documentation. It was decided to add it there because it was specifically related to managed dependencies, but there is a [link in the system requirements](https://docs.mendix.com/refguide/system-requirements/#firewall-settings) which takes you to the managed dependencies document.

Since this was set up quite recently, in discussion with the developers, I will not change the location of this information now. However, I will reassess this if we get more feedback like yours.

Thanks for wanting to make the documentation better and help others in the Mendix community.
Yours
Mark

**Comment by avotom** [comment]
Hi Mark,

thanks for your quick response and the very helpful information.

Kind regards,
Thomas
________________________________
