### ISSUE TITLE
Web service used on 'consume a simple web service' no longer active

### ISSUE THREAD

**Issue by robojobobobo** [mendix/docs#936]
The web service we use for the Consume a Simple Web Service example is no longer active
https://docs.mendix.com/howto/integration/consume-a-simple-web-service
The service is https://www.w3schools.com/xml/tempconvert.asmx
It is still visible, and the WSDL can be downloaded, but the underlying service no longer runs and returns a 301.  We should find a new service and update this.

**Comment by Adam-Dupaski** [comment]
Thanks for creating this issue @robojobobobo. We are looking into creating this web service ourselves with @joostverhoog.

**Comment by Adam-Dupaski** [comment]
@robojobobobo `https` is correct, but as you pointed out in Slack, the WSDL has an incorrect address in it. I've updated the how-to so that you override the location (there were also some missing steps in the doc). This should fix it for now, until a web service can be developed by the Integration team. Thanks to @RoelandSalij for the help.
